pipeline {
        agent{
            node{
                label 'AGENT-1'
            }
        }
  
        options {
            timeout(time: 1, unit: 'HOURS')
            disableConcurrentBuilds()
        }
  
    stages{
        stage('Init') {
            steps {
               sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
   
        stage('Plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
               """
            }
        }
        stage('Deploy') {
             input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
               """
            }
        }
    
    }
    post { 
        always {
            echo 'I will alwasy say hello!'
        }
        failure {
            echo 'this is run when pipelines failed, used generallt to send some alerts'
        }
        success {
            echo 'I will say hello pipeline is success'
        }
    }
}
    

